yolo_detector_node:
  ros__parameters:
    image_topic: "/camera/raw_frame"
    
    model: "/home/oytyeur/workspace/MGTS/Unitree/Go2Edu/vermilion/yolov8n.pt"
    # model: "/home/aboba/vermilion/yolov8n.pt"
    device: "cpu"
    detection_threshold: 0.5
    
    enable_tracking: true
    publish_annotated_image: true
    
    stats_interval_sec: 5.0
    
    qos_depth: 10
    reliability: "best_effort"
    
    target_classes: "person"
