yolo_detector_node:
  ros__parameters:
    # Читаемый топик
    image_topic: "/camera/raw_frame"

    # Путь до модели и выбор девайсв
    model: "src/perception/video/detection/yolo_detector/model/best2.pt"
    # device: "cpu"
    device: "cuda"

    # Настройка модели
    detection_threshold: 0.9
    enable_tracking: true
    tracker: "src/perception/video/detection/yolo_detector/config/custom_bytetrack.yaml"
    publish_annotated_image: true
    # Найстройка рвиза
    qos_depth: 10
    reliability: "best_effort"
    search_rubicks_cube: true
    